namespace Maryland.Stores
{
    /// <summary>
    /// Serializes <see cref="StoreDiff"/>s to <see cref="byte"/> streams.
    /// </summary>
    public interface IStoreDiffSerializer
    {
        /// <summary>
        /// Serializes a <see cref="StoreDiff"/> to a <see cref="byte"/> stream.
        /// </summary>
        /// <param name="storeDiff">The <see cref="StoreDiff"/> to serialize to a <see cref="byte"/> stream.</param>
        /// <returns>The <see cref="byte"/> stream generated by serializing the given <paramref name="storeDiff"/>.</returns>
        IEnumerable<byte> Serialize(StoreDiff storeDiff);
    }
}
