on: [push, pull_request]

jobs:
  php:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system:
        - windows-2022
        - windows-2019
        - ubuntu-22.04
        - ubuntu-20.04
        - ubuntu-18.04
        - macos-12
        - macos-11
        - macos-10.15
        php:
        - 5.6
        - 7.0
        - 7.1
        - 7.2
        - 7.3
        - 7.4
        - 8.0
        - 8.1
        exclude:
        - operating-system: windows-2022
          php: 5.6
        - operating-system: windows-2019
          php: 5.6
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      # Dependency patches.
      - run: rm composer.lock
        if: ${{ matrix.php != '8.1' }}
      - run: composer remove --dev vimeo/psalm phpunit/phpunit
        if: ${{ matrix.php == '5.6' }}
      - run: composer require --dev phpunit/phpunit:^5.0.0
        if: ${{ matrix.php == '5.6' }}
      - run: composer remove --dev vimeo/psalm phpunit/phpunit
        if: ${{ matrix.php == '7.0' }}
      - run: composer require --dev phpunit/phpunit:^6.5.0
        if: ${{ matrix.php == '7.0' }}
      - run: composer require --dev phpunit/phpunit:^7.5.0
        if: ${{ matrix.php == '7.1' }}
      - run: composer require --dev phpunit/phpunit:^8.5.0
        if: ${{ matrix.php == '7.2' }}

      - run: composer install
      - run: vendor/bin/psalm
        if: hashFiles('vendor/bin/psalm') != ''
      - run: mkdir -p test_results
      - run: vendor/bin/phpunit --whitelist src/php/src --coverage-text src/php/tests | tee test_results/unit
      - run: grep -E "^\s*Lines:\s*100\.00%\s*\([0-9]+\/[0-9]+\)\s*$" test_results/unit
        shell: bash
